"""init

Revision ID: 5c23adfde6cf
Revises: 
Create Date: 2025-08-07 13:44:27.295507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c23adfde6cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'activities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phones', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'organization_activities',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    # --- ФИКСТУРЫ ---
    conn = op.get_bind()

    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Медицина', NULL, 0)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Стоматология', 1, 1)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Ортодонтия', 2, 2)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Образование', NULL, 0)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Школы', 4, 1)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Гимназии', 5, 2)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('IT', NULL, 0)"))
    conn.execute(sa.text("INSERT INTO activities (name, parent_id, level) VALUES ('Разработка ПО', 7, 1)"))

    conn.execute(sa.text("""
        INSERT INTO buildings (address, latitude, longitude) VALUES
        ('ул. Пушкина, д. 10', 55.7558, 37.6173),
        ('пр. Ленина, д. 42', 59.9343, 30.3351),
        ('ул. Гагарина, д. 3', 56.8389, 60.6057),
        ('ул. Лесная, д. 7', 54.2048, 37.6115)
    """))

    conn.execute(sa.text("""
        INSERT INTO organizations (name, phones, building_id) VALUES
        ('Клиника Улыбка', ARRAY['+7 495 123-45-67'], 1),
        ('Школа №123', ARRAY['+7 812 555-66-77'], 2),
        ('Гимназия Эрудит', ARRAY['+7 343 888-99-00'], 3),
        ('SoftTech LLC', ARRAY['+7 495 222-33-44'], 4)
    """))

    conn.execute(sa.text("""
        INSERT INTO organization_activities (organization_id, activity_id) VALUES
        (1, 3),  -- Клиника Улыбка -> Ортодонтия
        (2, 5),  -- Школа №123 -> Школы
        (3, 6),  -- Гимназия Эрудит -> Гимназии
        (4, 8)   -- SoftTech LLC -> Разработка ПО
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_activities')
    op.drop_table('organizations')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
